#!/bin/bash
##
## One Lab to rule them all,
## One Lab to find them;
## One Lab to bring them all,
## and in the light bind them.
##
##   Powered by LabAstek
##

#tools
RED="\033[1;31m"
GREEN="\033[1;32m"
STD="\033[0;39m"

#user var
login=""
repository=""

####################
##   Users info   ##
####################
if [ $# -eq 2 ]
then
	login=$1
	repository=$2
else
	printf "Login : "
	read login
	printf "\nRepository : "
	read repository
fi

step()
{
	printf "\n=====\n"
	printf "$1"
	printf "\n=====\n\n"
}

warning() {	printf "${RED}$1${STD}\n"; }

validate() { printf "${GREEN}$1${STD}\n"; }

# turn in student work
make_rendu()
{
	cd "${HOME}/rendu/$repository"
	if [ $? -eq 1 ]
	then
		warning "[WARNING] Does your repository exist ?"
		echo "(couldn't cd to ${HOME}/rendu/$repository)"
		exit 1;
	fi
	rendu
}

get_diff()
{
	if [[ `diff $1 $2 | wc -l` -eq 0 ]]
	then
		validate "No diff"
		return 0
	else
		warning	"files differ !"
		diff $1 $2
		return 1
	fi
}

ssh_key_check()
{
	cat ~/.ssh/id_rsa_blih.pub > .rsa.local
	blih -u $login sshkey list > .rsa.serv
	get_diff .rsa.local .rsa.serv
}

# list all the file on the server
checkout()
{
	if [[ -z $SSH_AUTH_SOCK ]]
	then
		echo "-> ssh-agent"
		eval `ssh-agent`
	fi
	mkdir -p /tmp/random;
	cd /tmp/random;
	rm -rf ${repository};
    git clone "${login}@git.epitech.eu:/${login}/${repository}" > /dev/null;
    if [[ $? -ne 0 ]]
    then 
    	warning "Could not clone the repository"
    	exit -1;
    fi
    cd ${repository};
    ls -R > /tmp/random/diff.serv
    echo "--Files on the server :";
    cat /tmp/random/diff.serv
    cd ${HOME}/rendu/${repository};
    ls -R > /tmp/random/diff.local
    echo "--Making diff between local and server";
    get_diff /tmp/random/diff.local /tmp/random/diff.serv
	#rm -rf ${repository};
}

# check acl rights
moulinette_right()
{
	result="`blih -u $login repository getacl $repository`"
	if [[ `echo $result | grep 401 | wc -l` -eq 1 ]]
	then
		warning "[WARNING] Please check your password and your login."
	elif [[ `echo $result | grep ramassage-tek | wc -l` -eq 0 ]]
	then
		warning "[WARNING] The moulinette don't have any right !"
		printf "Trying to set up the rights for $RED$repository$STD :\n"
		blih -u $login repository setacl $repository ramassage-tek r
		echo "Checking again acl rights..."
	else
		echo "The following rights are set :"
		validate "$result"
		exit 1;
	fi
	moulinette_right
}


make_rendu
step "Checking sshkey..."
ssh_key_check
step "Checking if $RED$repository$STD is correctly turned in by $RED$login$STD login"
checkout
step "Checking if the right for the moulinette are set"
moulinette_right
